[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/questions"
  to = "/.netlify/functions/questions"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
